export const PRODUCTS = [
  {
    slug: "moco-go",
    name: "MOCO Go",
    image: "/assets/Product/mocoGO.png",
    price: 12900000,
    oldPrice: 15900000,
    store: "MOCO Official",
    subtitle: "Smart electric luggage",
    vi: "Phiên bản tiêu chuẩn với hệ thống lái điện tích hợp, hỗ trợ người dùng di chuyển thuận tiện tại sân bay, nhà ga, khu du lịch và các không gian rộng lớn.",
    en: "The standard edition with integrated electric driving for airports, stations, travel areas, and large spaces.",
  },
  {
    slug: "moco-plus",
    name: "MOCO Plus",
    image: "/assets/Product/mocoPLUS.png",
    price: 16900000,
    oldPrice: 19900000,
    store: "MOCO Official",
    subtitle: "GPS and auto-follow",
    vi: "Phiên bản vali điện có thể lái được, tích hợp hệ thống định vị GPS và chế độ tự động đi theo người dùng qua Bluetooth và ứng dụng điện thoại.",
    en: "A rideable electric luggage version with GPS positioning and automatic follow mode through Bluetooth and the mobile app.",
  },
  {
    slug: "moco-pro",
    name: "MOCO Pro",
    image: "/assets/Product/mocoPRO.png",
    price: 20900000,
    oldPrice: 24900000,
    store: "MOCO Official",
    subtitle: "Obstacle avoidance sensors",
    vi: "Phiên bản vali điện có thể lái được, tích hợp GPS, chế độ tự động đi theo người dùng và cảm biến tránh vật cản thông minh.",
    en: "A rideable electric luggage version with GPS, app connection, automatic follow mode, and intelligent obstacle avoidance sensors.",
  },
  {
    slug: "moco-max",
    name: "MOCO Max",
    image: "/assets/Product/mocoMAX.png",
    price: 24900000,
    oldPrice: 29900000,
    store: "MOCO Official",
    subtitle: "Full smart mobility suite",
    vi: "Phiên bản cao cấp nhất, tích hợp GPS, chế độ tự động đi theo người dùng, ứng dụng điện thoại và hệ thống cảm biến tránh vật cản toàn diện.",
    en: "The most advanced edition with GPS, Bluetooth app follow mode, and a complete intelligent obstacle avoidance system.",
  },
];
